imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: workflow/ }
    - { resource: "@AppBundle/Resources/config/services.yml" }
    - { resource: "@CoreBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    locales: [en, fr, de, es, it, pt]

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
        cookie_domain: ".%host%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'form/theme_horizontal.html.twig'
#        - 'bootstrap_3_layout.html.twig'
#        - 'bootstrap_3_horizontal_layout.html.twig'
    globals:
        upload_dir: "%upload_dir%"
        upload_docs_dir: "%upload_docs_dir%"
        upload_avatar_dir: "%upload_avatar_dir%"
        docs_local_path: "%docs_local_path%"
        favicon: "favicon.png"
        tinymce_key: "%tinymce_key%"
        locales: "%locales%"
        host: "%host%"

white_october_pagerfanta:
    default_view: custom_twitter_bootstrap3

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                options:
                    1002:  "SET NAMES 'UTF8'"
                mapping_types:
                    enum: string

            release:
                driver:   pdo_mysql
                host:     '%database_host%'
                port:     '%database_port%'
                dbname:   '%database_name_old%'
                user:     '%database_user%'
                password: '%database_password%'
                charset:  UTF8
                options:
                    1002:  "SET NAMES 'UTF8'"
                mapping_types:
                    enum: string

    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                dql:
                    datetime_functions:
                        DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat
                        DATEDIFF: DoctrineExtensions\Query\Mysql\DateDiff
                        DATE_ADD_EX: DoctrineExtensions\Query\Mysql\DateAdd
                        YEAR: DoctrineExtensions\Query\Mysql\Year
                        MONTH: DoctrineExtensions\Query\Mysql\Month
                        WEEK: DoctrineExtensions\Query\Mysql\Week
                        DAY: DoctrineExtensions\Query\Mysql\Day
                        HOUR: DoctrineExtensions\Query\Mysql\Hour
                        WEEKDAY: DoctrineExtensions\Query\Mysql\WeekDay
                        TIMESTAMPDIFF: DoctrineExtensions\Query\Mysql\TimestampDiff
                        FROM_UNIXTIME: DoctrineExtensions\Query\Mysql\FromUnixtime
                        DATE_SUB_EX: DoctrineExtensions\Query\Mysql\DateSub
                        NOW: DoctrineExtensions\Query\Mysql\Now
                    numeric_functions:
                        ROUND: DoctrineExtensions\Query\Mysql\Round
                    string_functions:
                        MD5: CoreBundle\DQL\MD5Function
                        FIELD: DoctrineExtensions\Query\Mysql\Field
                        IF: DoctrineExtensions\Query\Mysql\IfElse
                        GROUP_CONCAT: DoctrineExtensions\Query\Mysql\GroupConcat
                        MATCH_AGAINST: DoctrineExtensions\Query\Mysql\MatchAgainst
                        CAST: DoctrineExtensions\Query\Mysql\Cast
                mappings:
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias: GedmoTree # (optional) it will default to the name set for the mapping
                        is_bundle: false
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: false

            release:
                connection: release

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: CoreBundle\Entity\User
    service:
        mailer: core.service.mailer
    profile:
        form:
            type: UserBundle\Form\User\ProfileFormType
    registration:
        form:
            type: UserBundle\Form\User\RegistrationFormType
            validation_groups: [Registration]
        confirmation:
            enabled: true
    from_email:
        address: "%noreply_email%"
        sender_name: "%noreply_email%"
    resetting:
        form:
            type:               FOS\UserBundle\Form\Type\ResettingFormType
            name:               fos_user_resetting_form
            validation_groups:  [ResetPassword]

knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: KnpMenuBundle::menu.html.twig
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig

knp_snappy:
    pdf:
        enabled:    true
        binary:     '%knp_snappy_binary%'
        options:    []
    temporary_folder: "%kernel.cache_dir%/snappy"
    process_timeout: 20

stfalcon_tinymce:
    include_jquery: true
    tinymce_jquery: true
    selector: ".tinymce"
    language: "%locale%"
    theme:
        simple: ~
        advanced:
            plugins:
                - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                - "searchreplace wordcount visualblocks visualchars code fullscreen"
                - "insertdatetime media nonbreaking save table contextmenu directionality"
                - "emoticons template paste textcolor"
            toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
            toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | example"

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            tree: true
            softdeleteable: true
            timestampable: true
