# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    user.view.custom_twitter_bootstrap3_view:
        class: UserBundle\View\CustomTwitterBootstrap3View

    pagerfanta.view.custom_twitter_bootstrap3:
        class: UserBundle\View\CustomTwitterBootstrapTranslatedView
        arguments:
              - "@user.view.custom_twitter_bootstrap3_view"
              - "@translator"
        public: false
        tags: [{ name: pagerfanta.view, alias: custom_twitter_bootstrap3 }]

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
