<?php

namespace CoreBundle\Repository;

/**
 * CandidateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidateRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $ids
     * @return array
     */
    public function getCandidatesByIds($ids)
    {
        $qb = $this->createQueryBuilder('c');

        $qb
            ->innerJoin('c.waitingOrder', 'wo')
            ->innerJoin('wo.copywritingOrder', 'co')
            ->innerJoin('c.user', 'u')
            ->where($qb->expr()->in('c', $ids))
        ;

        return $qb->getQuery()->getResult();
    }
}
