<?php

namespace CoreBundle\Repository;

use CoreBundle\Entity\MetricsHistory;
use CoreBundle\Entity\Site;
use Doctrine\ORM\QueryBuilder;

/**
 * MetricsHistoryRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetricsHistoryRepository extends BaseRepository
{
    protected $filters = [
        'directory',
        'exchangeSite',
    ];

    /**
     * @param array $filters
     *
     * @return QueryBuilder
     */
    public function filter(array $filters)
    {
        $qb = $this->createQueryBuilder('mh');
        $this->prepare($filters, $qb);

        return $qb;
    }

    /**
     * @param Site $site
     *
     * @return MetricsHistory
     */
    public function getLatest(Site $site)
    {
        $qb = $this->createQueryBuilder('mh');

        $qb
            ->andWhere('mh.site = :site')
            ->setParameter('site', $site)
            ->setMaxResults(1)
            ->orderBy('mh.createdAt', 'DESC')
        ;

        $result = $qb->getQuery()->getResult();

        return !empty($result) ? $result[0] : null;
    }

    /**
     * @param $limit
     *
     * @return array
     */
    public function metricsForGoogleNewsUpdate($limit)
    {
        $qb = $this->createQueryBuilder('mh');

        $qb
            ->andWhere('mh.googleNews IS NULL')
            ->orderBy('mh.createdAt', 'ASC')
            ->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }
}
