<?php

namespace CoreBundle\Repository;

/**
 * ReplenishRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReplenishRequestRepository extends \Doctrine\ORM\EntityRepository implements FilterableRepositoryInterface
{
    /**
     * @inheritdoc
     */
    public function filter(array $filters, $count = false)
    {
        $qb = $this->createQueryBuilder('rr');

        if (isset($filters['requestType'])) {
            $qb->andWhere(
                $qb->expr()->eq('rr.requestType', $qb->expr()->literal($filters['requestType']))
            );
        }

        $qb->orderBy('rr.createdAt', 'desc');
        return $qb;
    }
}
